### ISSUE TITLE
General Issue: Too much infrastructure

### ISSUE THREAD

**Issue by pearsonca** [epiforecasts/ringbp#24]
You don't have tests, so get rid of the travis stuff.

You don't need to run this in docker - there's nothing complicated about the analysis, so figure out how to make it work across a sane set of environments, and get rid of that aspect. Your depends can specify which versions, which should be more than sufficient.

You have too many function files (basically one per function). That makes people dig around through files; there just isn't that much going on in this analysis - give them a single (or much smaller set of) source file(s) to scroll through.

These complaints would also be partially addressed if you fixed the related issue.

**Comment by pearsonca** [comment]
bumping this - I think a lot of this was addressed in #51, but there are still some lingering bits (e.g. the Dockerfile) that should be pruned (or moved to `inst/`, if maintaining a paper-analysis-repro)

**Comment by sbfnk** [comment]
Ah yes the Dockerfile is leftover - anything else? All the paper stuff lives in the [paper repo](https://github.com/cmmid/ringbp).

**Comment by pearsonca** [comment]
That was the main thing I noted - looks like you got all the old-approach-to-CI stuff.
