### ISSUE TITLE
Sloppy Formatting

### ISSUE THREAD

**Issue by pearsonca** [epiforecasts/ringbp#26]
The output of `lintr::lint_package()` is very long. It's not always right, but it's never this wrong.

**Comment by jhellewell14** [comment]
Output now only contains complaints about line lengths and snake case and other things that it is not right about such as global bindings. Considerably shorter. Closing

**Comment by pearsonca** [comment]
line lengths are still code smell, so don't be too dismissive of those.

process foul: which commit / merge closes this issue?

**Comment by jhellewell14** [comment]
Fixed in: https://github.com/epiforecasts/ringbp/commit/9d3d2925ca1a067d84cb1298b1b7c3c84c38aad2
